;Custom_OpenClash_Rules
;全分组防 DNS 泄漏订阅转换模板，项目基于 ACL4SSR 魔改而来
;设置方案：https://github.com/Aethersailor/Custom_OpenClash_Rules/wiki/OpenClash-%E8%AE%BE%E7%BD%AE%E6%96%B9%E6%A1%88
[custom]
;以下规则，按照从上往下的顺序遍历，优先命中上位规则，规则重复无影响
;修改顺序会影响分流效果

;cloudflare地址段
ruleset=🎯 全球直连,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Cloudflarecn/Cloudflarecn.list
ruleset=🌀 Cloudflare,clash-classic:https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Cloudflarecn/Cloudflarecn.yaml,28800
ruleset=🌀 Cloudflare,clash-classic:https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Cloudflare/Cloudflare.yaml,28800
;小米相关
ruleset=🎯 全球直连,clash-classic:https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/XiaoMi/XiaoMi.yaml,28800
;本项目收录的直连规则
ruleset=🎯 全球直连,clash-domain:https://cdn.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Direct_Domain.mrs,28800
ruleset=🎯 全球直连,clash-classic:https://cdn.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@main/rule/Custom_Direct_Classical_IP.yaml,28800
;域名直连
ruleset=🎯 全球直连,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/UnBan.list
;包括了 Telegram/WhatsApp/Line 等海外主流即时通讯软件域名
ruleset=💬 即时通讯,[]GEOSITE,category-communication
ruleset=💬 即时通讯,https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules/release/telegramcidr.txt
ruleset=💬 即时通讯,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=🧚 AI服务,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/AI.list
ruleset=🧚 AI服务,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/OpenAi.list
ruleset=👨‍💻 GitHub,clash-classic:https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GitHub/GitHub.yaml,28800
ruleset=👨‍💻 GitHub,[]GEOSITE,github
ruleset=🕐 测速工具,[]GEOSITE,category-speedtest
ruleset=📹 YouTube,clash-classic:https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/YouTube/YouTube.yaml,28800
ruleset=📹 YouTube,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ProxyMedia.list
ruleset=📺 社交媒体,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🍎 苹果服务,[]GEOSITE,apple
ruleset=☁️ 微软云盘,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/OneDrive.list
ruleset=Ⓜ️ 微软Bing,ttps://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Bing.list
ruleset=Ⓜ️ 微软服务,ttps://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Microsoft.list
ruleset=🌎 国外媒体,[]GEOSITE,category-entertainment
ruleset=🇬 谷歌服务,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/GoogleFCM.list
ruleset=🇬 谷歌服务,clash-classic:https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Google/Google.yaml,28800
ruleset=🇬 谷歌服务,clash-classic:https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GoogleDrive/GoogleDrive.yaml,28800
ruleset=🇬 谷歌服务,clash-classic:https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Mail/Mail.yaml,28800
ruleset=🇬 谷歌服务,clash-classic:https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GoogleFCM/GoogleFCM.yaml,28800
ruleset=🇬 谷歌服务,clash-classic:https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GoogleEarth/GoogleEarth.yaml,28800
;广告拦截
ruleset=🛑 全球拦截,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/BanProgramAD.list
ruleset=🛑 全球拦截,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/BanAD.list
;直连规则
ruleset=🎯 全球直连,https://cdn.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@refs/heads/main/rule/Custom_Direct.list
ruleset=🎯 全球直连,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Download.list
;代理规则
ruleset=🔰 手动选择,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ProxyGFWlist.list
ruleset=🔰 手动选择,https://cdn.jsdelivr.net/gh/Aethersailor/Custom_OpenClash_Rules@refs/heads/main/rule/Custom_Proxy.list
;保底规则
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位结束

;节点地区分组参考本项目推荐机场而设立
custom_proxy_group=💬 即时通讯`select`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🇹🇼 台湾节点`[]🇰🇷 韩国节点`[]🇩🇪 德国节点`[]⚡ 优选节点`[]🟩 电信节点`[]🟦 移动节点`[]🟨 联通节点`[]🍥 提取节点`[]🔰 手动选择`[]♻️ 自动选择
custom_proxy_group=📺 社交媒体`select`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🇹🇼 台湾节点`[]🇰🇷 韩国节点`[]🇩🇪 德国节点`[]⚡ 优选节点`[]🟩 电信节点`[]🟦 移动节点`[]🟨 联通节点`[]🍥 提取节点`[]🔰 手动选择`[]♻️ 自动选择
custom_proxy_group=🌀 Cloudflare`select`[]🎯 全球直连`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🇹🇼 台湾节点`[]🇰🇷 韩国节点`[]🇩🇪 德国节点`[]⚡ 优选节点`[]🟩 电信节点`[]🟦 移动节点`[]🟨 联通节点`[]🍥 提取节点`[]🔰 手动选择`[]♻️ 自动选择
custom_proxy_group=👨‍💻 GitHub`select`[]🎯 全球直连`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🇹🇼 台湾节点`[]🇰🇷 韩国节点`[]🇩🇪 德国节点`[]⚡ 优选节点`[]🟩 电信节点`[]🟦 移动节点`[]🟨 联通节点`[]🍥 提取节点`[]🔰 手动选择`[]♻️ 自动选择
custom_proxy_group=🧚 AI服务`select`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🇹🇼 台湾节点`[]🇰🇷 韩国节点`[]🇩🇪 德国节点`[]⚡ 优选节点`[]🟩 电信节点`[]🟦 移动节点`[]🟨 联通节点`[]🍥 提取节点`[]🔰 手动选择`[]♻️ 自动选择
custom_proxy_group=🌎 国外媒体`select`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🇹🇼 台湾节点`[]🇰🇷 韩国节点`[]🇩🇪 德国节点`[]⚡ 优选节点`[]🟩 电信节点`[]🟦 移动节点`[]🟨 联通节点`[]🍥 提取节点`[]🔰 手动选择`[]♻️ 自动选择
custom_proxy_group=🍎 苹果服务`select`[]🎯 全球直连`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🇹🇼 台湾节点`[]🇰🇷 韩国节点`[]🇩🇪 德国节点`[]⚡ 优选节点`[]🟩 电信节点`[]🟦 移动节点`[]🟨 联通节点`[]🍥 提取节点`[]🔰 手动选择`[]♻️ 自动选择
custom_proxy_group=☁️ 微软云盘`select`[]🎯 全球直连`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🇹🇼 台湾节点`[]🇰🇷 韩国节点`[]🇩🇪 德国节点`[]⚡ 优选节点`[]🟩 电信节点`[]🟦 移动节点`[]🟨 联通节点`[]🍥 提取节点`[]🔰 手动选择`[]♻️ 自动选择
custom_proxy_group=Ⓜ️ 微软Bing`select`[]🎯 全球直连`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🇹🇼 台湾节点`[]🇰🇷 韩国节点`[]🇩🇪 德国节点`[]⚡ 优选节点`[]🟩 电信节点`[]🟦 移动节点`[]🟨 联通节点`[]🍥 提取节点`[]🔰 手动选择`[]♻️ 自动选择
custom_proxy_group=Ⓜ️ 微软服务`select`[]🎯 全球直连`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🇹🇼 台湾节点`[]🇰🇷 韩国节点`[]🇩🇪 德国节点`[]⚡ 优选节点`[]🟩 电信节点`[]🟦 移动节点`[]🟨 联通节点`[]🍥 提取节点`[]🔰 手动选择`[]♻️ 自动选择
custom_proxy_group=📹 YouTube`select`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🇹🇼 台湾节点`[]🇰🇷 韩国节点`[]🇩🇪 德国节点`[]⚡ 优选节点`[]🟩 电信节点`[]🟦 移动节点`[]🟨 联通节点`[]🍥 提取节点`[]🔰 手动选择`[]♻️ 自动选择
custom_proxy_group=🇬 谷歌服务`select`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🇹🇼 台湾节点`[]🇰🇷 韩国节点`[]🇩🇪 德国节点`[]⚡ 优选节点`[]🟩 电信节点`[]🟦 移动节点`[]🟨 联通节点`[]🍥 提取节点`[]🔰 手动选择`[]♻️ 自动选择
custom_proxy_group=🕐 测速工具`select`[]🎯 全球直连`[]♻️ 自动选择`[]🍥 提取节点`[]🔰 手动选择`[]⚡ 优选节点
custom_proxy_group=🐟 漏网之鱼`select`[]🎯 全球直连`[]🛑 全球拦截`[]🍥 提取节点`[]♻️ 自动选择`[]🔰 手动选择`[]⚡ 优选节点`[]🟩 电信节点`[]🟦 移动节点`[]🟨 联通节点`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🇹🇼 台湾节点`[]🇰🇷 韩国节点`[]🇩🇪 德国节点
;设置节点分组标志位
custom_proxy_group=♻️ 自动选择`url-test`.*`https://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🔰 手动选择`select`[]♻️ 自动选择`.*`[]🎯 全球直连
custom_proxy_group=🇭🇰 香港节点`url-test`(🇭🇰|港|\bHK(?:[-_ ]?\d+(?:[-_ ]?[A-Za-z]{2,})?)?\b|hk|Hong Kong|HongKong|hongkong|HONG KONG|HONGKONG|深港|HKG|九龙|Kowloon|新界|沙田|荃湾|葵涌)`https://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇸 美国节点`url-test`(🇺🇸|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|纽约|纽纽|亚特兰大|迈阿密|华盛顿|\bUS(?:[-_ ]?\d+(?:[-_ ]?[A-Za-z]{2,})?)?\b|United States|UnitedStates|UNITED STATES|USA|America|AMERICA|JFK|EWR|IAD|ATL|ORD|MIA|NYC|LAX|SFO|SEA|DFW|SJC)`https://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本节点`url-test`(🇯🇵|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|日|\bJP(?:[-_ ]?\d+(?:[-_ ]?[A-Za-z]{2,})?)?\b|Japan|JAPAN|JPN|NRT|HND|KIX|TYO|OSA|关西|Kansai|KANSAI)`https://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇸🇬 新加坡节点`url-test`(🇸🇬|新加坡|坡|狮城|\bSG(?:[-_ ]?\d+(?:[-_ ]?[A-Za-z]{2,})?)?\b|Singapore|SINGAPORE|SIN)`https://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇹🇼 台湾节点`url-test`(🇹🇼|🇼🇸|台|新北|彰化|\bTW(?:[-_ ]?\d+(?:[-_ ]?[A-Za-z]{2,})?)?\b|Taiwan|TAIWAN|TWN|TPE|ROC)`https://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇰🇷 韩国节点`url-test`(🇰🇷|\bKR(?:[-_ ]?\d+(?:[-_ ]?[A-Za-z]{2,})?)?\b|Korea|KOREA|KOR|首尔|韩|韓|春川|Chuncheon|ICN)`https://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇩🇪 德国节点`url-test`(🇩🇪|德国|Germany|GERMANY|\bDE(?:[-_ ]?\d+(?:[-_ ]?[A-Za-z]{2,})?)?\b|DEU|柏林|法兰克福|慕尼黑|Munich|MUC)`https://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🟩 电信节点`url-test`(电信)`https://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🟦 移动节点`url-test`(移动)`https://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🟨 联通节点`url-test`(联通)`https://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🍥 提取节点`url-test`(提取)`https://www.gstatic.com/generate_204`300,,50
custom_proxy_group=⚡ 优选节点`url-test`^(?!.*(🇭🇰|港|HK|Hong|🇺🇸|美|US|United|States|USA|America|🇯🇵|日|JP|Japan|🇸🇬|坡|SG|Singapore|🇹🇼|台|TW|Taiwan|🇰🇷|韩|KR|Korea|🇩🇪|德|DE|Germany|电信|移动|联通)).*`https://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🎯 全球直连`select`(直连)
custom_proxy_group=🛑 全球拦截`select`[]REJECT
;下方参数请勿修改
enable_rule_generator=true
overwrite_original_rules=true
